"""add_qty_to_trade

Revision ID: 1bfe0eba63d3
Revises: 38dca0b8fe0f
Create Date: 2026-06-13 22:14:58.741382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bfe0eba63d3'
down_revision: Union[str, None] = '38dca0b8fe0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('trades', sa.Column('qty', sa.Integer(), nullable=True, comment='Current open quantity (contracts)'))
    # Set default value for existing rows (calculate from cash events)
    op.execute("""
        UPDATE trades SET qty = COALESCE((
            SELECT SUM(CASE WHEN event_type = 'OPEN' THEN qty ELSE -qty END)
            FROM cash_events
            WHERE cash_events.trade_id = trades.id
        ), 0)
    """)
    # Now make it not null
    op.alter_column('trades', 'qty', nullable=False, server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trades', 'qty')
    # ### end Alembic commands ###
