"""add_direction_strikes_to_trade

Revision ID: 38dca0b8fe0f
Revises: 002_rls
Create Date: 2026-06-13 21:35:44.312300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '38dca0b8fe0f'
down_revision: Union[str, None] = '002_rls'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('billing', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='free, trialing, active, canceled, past_due')
    op.alter_column('billing', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_comment='free, pro')
    op.alter_column('billing', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cash_events', 'qty',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cash_events', 'misc_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('cash_events', 'commissions',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.drop_index(op.f('ix_cash_events_trade_id'), table_name='cash_events')
    op.alter_column('imports', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('imports', 'raw_events',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('imports', 'trades_created',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('imports', 'trades_updated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_imports_user_id'), table_name='imports')
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_trade_legs_trade_id'), table_name='trade_legs')
    op.add_column('trades', sa.Column('open_direction', sa.String(length=10), nullable=True, comment='BUY or SELL at open'))
    op.add_column('trades', sa.Column('strikes', sa.ARRAY(sa.Numeric(precision=12, scale=2)), nullable=True, comment='Array of strike prices'))
    op.add_column('trades', sa.Column('option_type', sa.String(length=10), nullable=True, comment='CALL or PUT'))
    op.alter_column('trades', 'import_id',
               existing_type=sa.UUID(),
               comment='Which import created this trade (not FK for security)',
               existing_comment='Which import created this trade',
               existing_nullable=True)
    op.alter_column('trades', 'spread_label',
               existing_type=sa.VARCHAR(length=50),
               comment='Raw TOS label (VERTICAL, BUTTERFLY, etc.)',
               existing_comment='Raw TOS label',
               existing_nullable=True)
    op.alter_column('trades', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('trades', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('trades', 'close_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               comment='Net cash at close')
    op.alter_column('trades', 'total_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('trades', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_comment='Gross P&L before fees')
    op.alter_column('trades', 'realized_pnl_net',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False,
               existing_comment='Net P&L after fees')
    op.alter_column('trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trades', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('trades', 'realized_pnl_net',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_comment='Net P&L after fees')
    op.alter_column('trades', 'realized_pnl',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               existing_comment='Gross P&L before fees')
    op.alter_column('trades', 'total_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('trades', 'close_amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True,
               comment=None,
               existing_comment='Net cash at close')
    op.alter_column('trades', 'is_expired',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('trades', 'is_closed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('trades', 'spread_label',
               existing_type=sa.VARCHAR(length=50),
               comment='Raw TOS label',
               existing_comment='Raw TOS label (VERTICAL, BUTTERFLY, etc.)',
               existing_nullable=True)
    op.alter_column('trades', 'import_id',
               existing_type=sa.UUID(),
               comment='Which import created this trade',
               existing_comment='Which import created this trade (not FK for security)',
               existing_nullable=True)
    op.drop_column('trades', 'option_type')
    op.drop_column('trades', 'strikes')
    op.drop_column('trades', 'open_direction')
    op.create_index(op.f('ix_trade_legs_trade_id'), 'trade_legs', ['trade_id'], unique=False)
    op.alter_column('profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_imports_user_id'), 'imports', ['user_id'], unique=False)
    op.alter_column('imports', 'trades_updated',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('imports', 'trades_created',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('imports', 'raw_events',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('imports', 'imported_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_cash_events_trade_id'), 'cash_events', ['trade_id'], unique=False)
    op.alter_column('cash_events', 'commissions',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('cash_events', 'misc_fees',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('cash_events', 'qty',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('billing', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('billing', 'subscription_tier',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='free, pro')
    op.alter_column('billing', 'subscription_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_comment='free, trialing, active, canceled, past_due')
    # ### end Alembic commands ###
